"""Theme pass criteria

Revision ID: 8a6752864b97
Revises: b4514380383e
Create Date: 2023-05-27 11:46:40.034286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6752864b97'
down_revision = 'b4514380383e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_criteria', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_column('pass_criteria')

    # ### end Alembic commands ###
